version: '2'

services:
  server:
    image: 'dreambuildr-server:latest'
    build:
      context: .
    container_name: server
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://database/dreambuildr_db
      - DB_USERNAME=dreambuildr_db
      - DB_PASSWORD=y6SqGyddBqL!_%>B

  database:
    image: 'postgres:14-alpine'
    container_name: database
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=dreambuildr_db
      - POSTGRES_PASSWORD=y6SqGyddBqL!_%>B

  react-client:
    image: 'dreambuildr-client:latest'
    build:
      context: ../frontend
    container_name: client
    ports:
      - "80:3000"
